typedef struct DebuffEntry DebuffEntry;
typedef struct BuffDebuff_Struct BuffDebuff_Struct;

void UnitApplyBuff(struct Unit* unit,u8 buffID);
void UnitApplyDebuff(struct Unit* unit,u8 buffID);
void UnitClearBuffs(struct Unit* unit);
int UnitHasABuff(struct Unit* unit);
int UnitHasADebuff(struct Unit* unit);
void UnitClearDebuffs(struct Unit* unit);
void UnitApplyBuffWithBonusDur(struct Unit* unit,u8 buffID,u8 bonusDuration);
struct DebuffEntry* GetUnitBuffsDebuffs(struct Unit* unit);

enum {
	BUFF_NONE = 0,
	BUFF_VANGUARD,
	BUFF_NATURALLEADER,
	BUFF_BERSERKERVOW1,
	BUFF_BERSERKERVOW2,
	BUFF_BERSERKERVOW3,
	BUFF_SUREAIM1,
	BUFF_SUREAIM2,
	BUFF_PANACAEA,
	BUFF_IMMUNIZE1,
	BUFF_IMMUNIZE2,
	BUFF_IMMUNIZE3,
	BUFF_RALLYINGFLAG1,
	BUFF_RALLYINGFLAG2,
	BUFF_SURVIVALFLAG1,
	BUFF_SURVIVALFLAG2,
	BUFF_EXPERTISEFLAG1,
	BUFF_EXPERTISEFLAG2,
	BUFF_CHARGECOMMAND1,
	BUFF_CHARGECOMMAND2,
	BUFF_CHARGECOMMAND3,
	BUFF_CHARGECOMMAND4,
	BUFF_CHARGECOMMAND5,
	BUFF_GALLOP1,
	BUFF_GALLOP2,
	BUFF_GALLOP3,
	BUFF_RAIDCOMMAND1,
	BUFF_RAIDCOMMAND2,
	BUFF_RAIDCOMMAND3,
	BUFF_RAIDCOMMAND4,
	BUFF_RAIDCOMMAND5,
	BUFF_BRAVERY1,
	BUFF_BRAVERY2,
	BUFF_BRAVERY3,
	BUFF_SHELTER1,
	BUFF_SHELTER2,
	BUFF_SHELTER3,
	BUFF_MERCURY1,
	BUFF_MERCURY2,
	BUFF_MERCURY3,
	BUFF_INSIGHT1,
	BUFF_INSIGHT2,
	BUFF_INSIGHT3,
	BUFF_FLEETING1,
	BUFF_FLEETING2,
	BUFF_FLEETING3,
	BUFF_MAGUSRUNE1,
	BUFF_MAGUSRUNE2,
	BUFF_REVOLUTIONRUNE1,
	BUFF_REVOLUTIONRUNE2,
	BUFF_AGILITYRUNE1,
	BUFF_AGILITYRUNE2,
	BUFF_MOONRISE1,
	BUFF_MOONRISE2,
	BUFF_MOONRISE3,
	BUFF_MOONRISE4,
	BUFF_MOONRISE5,
	BUFF_PRECISION1,
	BUFF_PRECISION2,
	BUFF_PRECISION3,
	BUFF_BLOODFURY,
	BUFF_BLOODRUSH,
	BUFF_SPIRITSHIELD1,
	BUFF_SPIRITSHIELD2,
	BUFF_BLOODYOFFENSE1,
	BUFF_BLOODYOFFENSE2,
	BUFF_SCAPEGOAT1,
	BUFF_SCAPEGOAT2,
	BUFF_SCAPEGOAT3,
	BUFF_RESILIENTWINGS1,
	BUFF_RESILIENTWINGS2,
	BUFF_SWIFTWINGS1,
	BUFF_SWIFTWINGS2,
	BUFF_WINGEDGALLOP1,
	BUFF_WINGEDGALLOP2,
	BUFF_MERCYSWINGS1,
	BUFF_MERCYSWINGS2,
	BUFF_MERCYSWINGS3,
	BUFF_DRACONICFURY1,
	BUFF_DRACONICFURY2,
	BUFF_HERBBOOST1,
	BUFF_HERBBOOST2,
	BUFF_HERBBOOST3,
	BUFF_FURYHERB1,
	BUFF_FURYHERB2,
	BUFF_FURYHERB3,
	BUFF_SOULSHIELD1,
	BUFF_SOULSHIELD2,
	BUFF_SOULCHARGE1,
	BUFF_SOULCHARGE2,
	BUFF_REBOUND,
	BUFF_BRAVANT,
	BUFF_STONARD,
	BUFF_NOBLEBUFFSLOT1,
	BUFF_NOBLEBUFFSLOT2,
	BUFF_NOBLEBUFFSLOT3,
	BUFF_NOBLEBUFFSLOT4,
	BUFF_NOBLEBUFFSLOT5,
	BUFF_NOBLEBUFFSLOT6,
	BUFF_NOBLEBUFFSLOT7,
	BUFF_NOBLEBUFFSLOT8,
	BUFF_NOBLEBUFFSLOT9,
	BUFF_NOBLEBUFFSLOT10,
	BUFF_NOBLEBUFFSLOT11,
	BUFF_NOBLEBUFFSLOT12,
	BUFF_NOBLEBUFFSLOT13,
	BUFF_NOBLEBUFFSLOT14,
	BUFF_NOBLEBUFFSLOT15,
	BUFF_NOBLEBUFFSLOT16,
	BUFF_FIERCEAURA,
	BUFF_SHIELDAURA,
	BUFF_HASTEAURA,
	BUFF_PRECISEAURA,
};

enum {
	DEBUFF_NONE = 0,
	DEBUFF_GUARDBREAK,
	DEBUFF_POWERBREAK,
	DEBUFF_AGILITYBREAK,
	DEBUFF_SHIELDCRUSH,
	DEBUFF_WARCRY1,
	DEBUFF_WARCRY2,
	DEBUFF_HELLISHCRY1,
	DEBUFF_HELLISHCRY2,
	DEBUFF_DOMINANTCRY1,
	DEBUFF_DOMINANTCRY2,
	DEBUFF_WARNINGSHOT1,
	DEBUFF_WARNINGSHOT2,
	DEBUFF_SHININGFORCE,
	DEBUFF_WARSAP,
	DEBUFF_MISFORTUNE,
	DEBUFF_SAPPING1,
	DEBUFF_SAPPING2,
	DEBUFF_FRAILTY1,
	DEBUFF_FRAILTY2,
	DEBUFF_LEADEN1,
	DEBUFF_LEADEN2,
	DEBUFF_CRIPPLEWHIP1,
	DEBUFF_CRIPPLEWHIP2,
	DEBUFF_CRIPPLEWHIP3,
	DEBUFF_CRIPPLEWHIP4,
	DEBUFF_CRIPPLEWHIP5,
	DEBUFF_STIGMATA1,
	DEBUFF_STIGMATA2,
	DEBUFF_STIGMATA3,
	DEBUFF_CLOSECOMBAT,
	DEBUFF_TRICKERY1,
	DEBUFF_TRICKERY2,
	DEBUFF_SAPPINGARROW,
	DEBUFF_PREDATORSARROW,
	DEBUFF_RESONANTROAR1,
	DEBUFF_RESONANTROAR2,
	DEBUFF_SLUGGISHHERB1,
	DEBUFF_SLUGGISHHERB2,
	DEBUFF_FRAGILEHERB1,
	DEBUFF_FRAGILEHERB2,
	DEBUFF_CORROSIVEHERB,
	DEBUFF_CHARMINGCIRCLE1,
	DEBUFF_CHARMINGCIRCLE2,
	DEBUFF_ATROPHICCIRCLE1,
	DEBUFF_ATROPHICCIRCLE2,
	DEBUFF_HAZECURTAIN1,
	DEBUFF_HAZECURTAIN2,
	DEBUFF_HAZECURTAIN3,
	DEBUFF_SAPPINGSTANCE1,
	DEBUFF_SAPPINGSTANCE2,
	DEBUFF_SAPPINGSTANCE3,
	DEBUFF_IGNITION1,
	DEBUFF_IGNITION2,
	DEBUFF_IGNITION3,
	DEBUFF_BREAKINGPULSE1,
	DEBUFF_BREAKINGPULSE2,
	DEBUFF_BREAKINGPULSE3,
	DEBUFF_SAPPINGAURA,
	DEBUFF_FRAILTYAURA,
	DEBUFF_SLUGGISHAURA,
	DEBUFF_MISTYAURA,
	DEBUFF_MAGUSRUNE1,
	DEBUFF_MAGUSRUNE2,
	DEBUFF_REVOLUTIONRUNE1,
	DEBUFF_REVOLUTIONRUNE2,
	DEBUFF_AGILITYRUNE1,
	DEBUFF_AGILITYRUNE2,
};


struct DebuffEntry{
	/* 00 */ u8 buff1;
	/* 01 */ u8 buff2;
	/* 02 */ u8 buff3;
	/* 03 */ u8 buff1dur: 2;
	/* 03 */ u8 buff2dur: 2;
	/* 03 */ u8 buff3dur: 2;
	/* 03 */ u8 pad1: 2;
	/* 04 */ u8 debuff1;
	/* 05 */ u8 debuff2;
	/* 06 */ u8 debuff3;
	/* 07 */ u8 debuff1dur: 2;
	/* 07 */ u8 debuff2dur: 2;
	/* 07 */ u8 debuff3dur: 2;
	/* 07 */ u8 pad2: 2;
};

extern struct DebuffEntry gBuffDebuffTable[132];

struct BuffDebuff_Struct
{
	u16 buffName;
	u16 buffDesc;
	u8 buffDuration;
	u8 atkMul;
	u8 atkDiv;
	u8 hitMul;
	u8 hitDiv;
	u8 avoMul;
	u8 avoDiv;
	u8 critMul;
	u8 critDiv;
	u8 asMul;
	u8 asDiv;
	u8 defMul;
	u8 defDiv;
	u8 lucMul;
	u8 lucDiv;
	u8 movMod;
};


extern struct BuffDebuff_Struct BuffEffectsTable[0xff]; 
extern struct BuffDebuff_Struct DebuffEffectsTable[0xff]; 